version: "3"
services:
  nest:
    build:
      context: ./api
    container_name: "${NEST}"
    ports:
      - "${NEST_EXTERNAL_PORT}:${NEST_PORT}"
    restart: "unless-stopped"
    env_file:
      - ./.env
