version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: "${MONGO}"
    ports:
      - "${MONGO_EXTERNAL_PORT}:${MONGO_PORT}"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/backup:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
